# Project information
site_name: "TAO Publisher"
site_description: "TAO application publisher API/CLI"
site_author: "CS Group"
copyright: "Copyright &copy; 2024, CS Group"

# Repository
repo_name: "tao-org/tao-publisher"
repo_url: "https://github.com/tao-org/tao-publisher"
edit_uri: edit/master/docs/src

# Configuration
site_dir: "build/html"
docs_dir: "src"
theme:
  name: material
  language: en
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for auto-system mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to light mode

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - mkdocs-click
  - pymdownx.snippets:
      base_path: ["..", "src"]
      check_paths: true
  - toc:
      permalink: true

# Plugins
plugins:
  - search
  - tags
  - section-index
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [../src]
          options:
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: list
            docstring_style: google
            group_by_category: true
            heading_level: 1
            line_length: 88
            merge_init_into_class: true
            separate_signature: true
            show_bases: true
            show_category_heading: true
            show_root_heading: true
            show_root_toc_entry: true
            show_signature_annotations: true
            show_source: false
            summary: true
            unwrap_annotated: true

# Page tree
nav:
  - Home:
      - Overview: index.md
      - About:
        - Changelog: changelog.md
        - License: license.md
  - Getting started:
      - Installation: getting-started/installation.md
      - Configuration: getting-started/configuration.md
      - Usage: getting-started/usage.md
      - CLI reference: getting-started/cli_reference.md
      - API reference: getting-started/api_reference.md
  - API Reference: reference/
  - Development:
      - Contributing: development/contributing.md
      - Source code: "https://github.com/tao-org/tao-publisher"
      - Issues: "https://github.com/tao-org/tao-publisher/issues"

# Footer links
extra:
  social:
    - icon: fontawesome/brands/git-alt
      link: https://github.com/tao-org/tao-publisher
    - icon: fontawesome/solid/globe
      link: https://www.csgroup.eu
